params:
  seed: 1
  env:
    clip_actions: 1.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init: {name: default}
        sigma_init: {name: const_initializer, val: 0}
        fixed_sigma: true
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer: {name: default, scale: 2}
  config:
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    name: starling2max_velocity_px4_port
    reward_shaper: {scale_value: 0.1}
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    ppo: true
    learning_rate: 1.0e-4
    lr_schedule: adaptive
    kl_threshold: 0.016
    save_best_after: 10
    score_to_win: 100000
    grad_norm: 1.0
    entropy_coef: 0.0001
    truncate_grads: true
    e_clip: 0.2
    clip_value: false
    horizon_length: 32
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    normalize_input: false
    normalize_value: true
    bounds_loss_coef: 0.0001
    max_epochs: 1000
    player: {render: false, deterministic: true, games_num: 100000}
